const clients = [
  {
    id: "1",
    clientName: "Oak",
    imageThumb: "/images/logos/oak-logo-main.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  // {
  //   id: "2",
  //   clientName: "Oak Classroom & Teacher Hub",
  //   imageThumb: "/images/logos/oak-logo-two.png",
  //   displayImage: "",
  //   ux: true,
  //   graphic: true,
  //   dev: true,
  // },
  {
    id: "3",
    clientName: "Pentland Disruption Lab",
    project: "Berghaus",
    imageThumb: "/images/logos/berghaus-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: false,
  },
  {
    id: "4",
    clientName: "Pentland Disruption Lab",
    project: "Hayst",
    imageThumb: "/images/logos/hayst-logo.png",
    displayImage: "",
    ux: true,
    graphic: false,
    dev: true,
  },
  {
    id: "5",
    clientName: "Pentland Disruption Lab",
    project: "Toddl",
    imageThumb: "/images/logos/todl-logo.png",
    displayImage: "",
    ux: true,
    graphic: false,
    dev: false,
  },
  {
    id: "6",
    clientName: "Edapt",
    imageThumb: "/images/logos/edapt.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "7",
    clientName: "John Roberts",
    project: "Center for education and youth",
    agency: true,
    imageThumb: "/images/logos/cfey-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "8",
    clientName: "Climbpass",
    imageThumb: "/images/logos/climbpass-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: false,
  },
  {
    id: "12",
    clientName: "Putty Studio",
    project: "SOWN",
    imageThumb: "/images/logos/sown-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "9",
    clientName: "Putty Studio",
    project: "Beginning Middle and End",
    imageThumb: "/images/logos/bme-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "10",
    clientName: "Revere",
    project: "Gone West",
    imageThumb: "/images/logos/gonewest-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "11",
    clientName: "Matt Bay",
    project: "Flipbook Studio",
    imageThumb: "/images/logos/flipbook-logo.png",
    displayImage: "",
    ux: false,
    graphic: false,
    dev: true,
  },
  {
    id: "12",
    clientName: "Battalion",
    project: "Coherent Labs",
    imageThumb: "/images/logos/coherentlabs-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "13",
    clientName: "Battalion",
    project: "APX",
    imageThumb: "/images/logos/apx-logo.png",
    displayImage: "",
    ux: false,
    graphic: false,
    dev: true,
  },
  {
    id: "14",
    clientName: "Teacher Tapp",
    imageThumb: "/images/logos/teachertap-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: true,
  },
  {
    id: "15",
    clientName: "Dough",
    imageThumb: "/images/logos/dough-logo.png",
    displayImage: "",
    ux: false,
    graphic: false,
    dev: true,
  },
  {
    id: "16",
    clientName: "WeWork",
    imageThumb: "/images/logos/wework-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
  {
    id: "17",
    clientName: "Love, Corn",
    imageThumb: "/images/logos/lovecorn-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
  {
    id: "18",
    clientName: "M&S",
    imageThumb: "/images/logos/mns-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
  {
    id: "19",
    clientName: "CEEK",
    project: "Table Talk",
    imageThumb: "/images/logos/tabletalk-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
  {
    id: "20",
    clientName: "Push Doctor",
    imageThumb: "/images/logos/pushdoctor-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
  {
    id: "21",
    clientName: "Startist",
    imageThumb: "/images/logos/startist-logo.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "21",
    clientName: "Settio",
    imageThumb: "/images/logos/settio-logo.png",
    displayImage: "",
    ux: false,
    graphic: true,
    dev: false,
  },
];
export default clients;
